GROUP_ID          = io.github.rosaleskevin
ARTIFACT_ID       = cot-kmp
VERSION           = 0.1.0-alpha05

POM_NAME          = cot-kmp
POM_DESCRIPTION   = Lightweight Kotlin Multiplatform library for parsing, generating, and transforming Cursor on Target (COT) messages with MIL-STD-2525C/D SIDC support.
POM_URL           = https://github.com/rosalesKevin/cot-kmp
POM_LICENSE_NAME  = MIT License
POM_LICENSE_URL   = https://opensource.org/licenses/MIT
POM_LICENSE_DIST  = repo
POM_SCM_URL       = https://github.com/rosalesKevin/cot-kmp
POM_SCM_CONN      = scm:git:git://github.com/rosalesKevin/cot-kmp.git
POM_SCM_DEV_CONN  = scm:git:ssh://git@github.com/rosalesKevin/cot-kmp.git
POM_DEVELOPER_ID  = rosalesKevin
POM_DEVELOPER_NAME = Kevin Klein Rosales
POM_DEVELOPER_URL = https://github.com/rosalesKevin
